id = "cobol"
name = "COBOL"
description = "COBOL language server and syntax highlighting"
version = "0.0.2"
schema_version = 1
authors = ["William Walker <w_walker@icloud.com>"]
repository = "https://github.com/willswire/zed-cobol"

[language_servers.cobol]
name = "COBOL Language Server"
language = "COBOL"

[grammars.cobol]
repository = "https://github.com/willswire/tree-sitter-cobol"
commit = "934ac8b118f59bdc6827b0a322ebd94117f0509b"
